heat_template_version: 2018-08-31

parameters:
  stack:
    type: string
  image:
    type: string
  flavor:
    type: string
  security_group:
    label: Cluster SG
    type: string
  network: 
    type: string
  public_network:
    type: string
  key_pair:
    type: string

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { list_join: [".", [{ get_param: "stack" }, bastion]] }
      key_name: { get_param: key_pair }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port }

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
      security_groups:
        - { get_resource: bastion_security_group }
        - { get_param: security_group }

  bastion_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { list_join: [".", [{ get_param: "stack" }, bastion-security-group]] }
      rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 22
          port_range_max: 22

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }

outputs:
  address: 
    value: {get_attr: [floating_ip, 'floating_ip_address']}