heat_template_version: 2018-08-31

parameters:
  public_network:
    type: string
  image:
    type: string
  flavor:
    type: string
  public_key:
    type: string

resources:

  bastion:
    type: bastion.yaml
    properties:
      stack: { get_param: 'OS::stack_name' }
      network: { get_attr: ['network', 'main'] }
      public_network: { get_param: public_network }
      image: { get_param: image }
      flavor: { get_param: flavor}
      security_group: { get_attr: [security, security_group] }
      key_pair: { get_attr: [security, 'key_pair'] }
  
  controlplane:
    type: controlplane.yaml
    properties:
      count: 1
      stack: { get_param: 'OS::stack_name' }
      network: { get_attr: ['network', 'main'] }
      image: { get_param: image }
      flavor: { get_param: flavor}
      security_group: { get_attr: [security, security_group] }
      key_pair: { get_attr: [security, 'key_pair'] }

  worker:
    type: workerplane.yaml
    properties:
      count: 1
      stack: { get_param: 'OS::stack_name' }
      network: { get_attr: ['network', 'main'] }
      image: { get_param: image }
      flavor: { get_param: flavor}
      security_group: { get_attr: [security, security_group] }
      key_pair: { get_attr: [security, 'key_pair'] }

  network:
    type: network.yaml
    properties:
      stack: { get_param: 'OS::stack_name' }
      public_network: { get_param: public_network }

  security:
    type: security.yaml
    properties:
      stack: { get_param: 'OS::stack_name' }
      public_key: { get_param: 'public_key' }


outputs:
  bastion:
    value: {get_attr: [bastion, 'address']}
  controlplane:
    value: {get_attr: [controlplane, address]}
  worker:
    value: {get_attr: [worker, address]}
    