heat_template_version: 2018-08-31

parameters:
  stack:
    type: string
  public_key:
    type: string

resources:
  key_pair:
    type: OS::Nova::KeyPair
    properties:
      name: { list_join: ["-", [{ get_param: "stack" }, key-pair]] }
      public_key: { get_param: 'public_key' }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { list_join: [".", [{ get_param: "stack" }, security-group]] }

  security_group_rule_tcp:
    type: OS::Neutron::SecurityGroupRule
    properties:
      direction: ingress
      protocol: tcp
      remote_group: { get_resource: security_group }
      security_group: { get_resource: security_group }
  security_group_rule_udp:
    type: OS::Neutron::SecurityGroupRule
    properties:
      direction: ingress
      protocol: udp
      remote_group: { get_resource: security_group }
      security_group: { get_resource: security_group }

outputs:
  security_group:
    value: { get_resource: security_group }
  key_pair:
    value: { get_resource: key_pair }